### PR TITLE
support callback function after timer

### PR DESCRIPTION
**Pull request by kraeki**
Example: 
==========

swal({
    title: "foo succesful!",
    type: "success",
    timer: 2000
},
function(){
  // reload page after swal-dialog closes
  location.reload();
});

### CODE REVIEW

**Comment by mromagnoli** [comment]
+1 
I also would include a callback not only for 'timer' option but all 'done events'

**Comment by adrianoresende** [comment]
I need this too.

+1

**Comment by WaSa42** [comment]
+1

**Comment by t4t5** [comment]
This has finally been added in v1.0.0. Went with another pull request since the file structure has changed considerably since November. Thanks for the suggestion!

**Pull request closed without merging**
