### PR TITLE
adding a cancelButtonColor option

### PR DESCRIPTION
**Pull request by fiote**
NEW OPTION ADDED:
name: cancelButtonColor 
default: #C1C1C1
description: Use this to change the background color of the "Cancel"-button (must be a HEX value).

### CODE REVIEW

**Comment by thomasmorelli** [comment]
@fiote Could you compress this and add it to the minified version?

**Comment by fiote** [comment]
@thomasmorelli Just pushed the minified file =)

**Comment by thomasmorelli** [comment]
@fiote Thanks :+1:

**Comment by fracz** [comment]
+1

**Comment by t4t5** [comment]
I decided to take another approach in SweetAlert 2.0 and deprecate `confirmButtonColor` instead. All styling changes are now [done in CSS](https://sweetalert.js.org/docs/#theming).

**Pull request closed without merging**
