### PR TITLE
Countdown support for timer function

### PR DESCRIPTION
**Pull request by muratbastas**
This adds a countdown timer optionaly.

If **html** set to **true** and **text** **&lt;strong class="sa-timer-countdown"&gt;&lt;strong&gt;** contains when using timer, the countdown function will run.

Example usage:
```
swal({
	title: "Auto close alert!",
	text: "I will close in <strong class=\"sa-timer-countdown\">4</strong> seconds.",
	timer: 4000,
	html: true,
	showConfirmButton: false
});
```

I'm sorry if my english sucks.

### CODE REVIEW

**Comment by eterry1388** [comment]
Why not contribute to the active project here? https://github.com/limonte/sweetalert2

**Comment by muratbastas** [comment]
@eterry1388 is this repo not active? 😕

**Comment by eterry1388** [comment]
@muratbastas The last commit was 6 months ago, there are 177 open issues, and 56 open merge requests.  So yes, it does appear to be a neglected project.

**Comment by muratbastas** [comment]
@eterry1388 okay. I'll create pr at limonte/sweetalert2 as one commit. Thanks for notice.

**Pull request closed without merging**
