### PR TITLE
IE 11 Bugfixes

### PR DESCRIPTION
**Pull request by lionralfs**
Hello there 👋

I went ahead and fixed some of the issues regarding IE11 compatibility referenced [here](https://github.com/t4t5/sweetalert/issues/611).
It basically boiled down to a few features which IE11 doesn't support:

- `.forEach()` on a `NodeList`
- `.fetch()` which is used in an example (I've included a polyfill)
- Template Strings
- `Object.assign()` (polyfilled)
- Promises (polyfilled)
- Arrow Functions

Took me quite some time to figure out why some of these things didn't get transpiled by Babel. But the code is actually being pulled from the page and used in an `eval()`. This might be something to improve in the future.

Also, is there any specific reason why files like `docs/assets/js/index.js` are not being .gitignore'd?

### CODE REVIEW

**Comment by t4t5** [comment]
Hi @lionralfs, and thank you so much for helping out with this PR!

A couple of thoughts:

- Let's add `whatwg-fetch` to `devDependencies` instead, since it's only used on the docs page, and not for the library itself.
- How about using [this polyfill](https://www.npmjs.com/package/nodelist-foreach-polyfill) for `NodeList` and `.forEach`? I'd like to preserve the `forEach` syntax just for better readability :)
- I think we should encourage users to adopt `ES2015` syntax so I'm a bit reluctant to merging the changes on the docs page that change `=>` to `function()` for example. Maybe we can use babel and do something like this:
```javascript
eval(babel.transform('<div>some ES2015 code</div>', {
  presets : [ 'babel-preset-es2015' ] 
}).code)
```

I'm aware that using `eval` is terrible btw, but it makes maintaining the documentation examples so much easier. :P

**Comment by lionralfs** [comment]
Thanks for your reply.

I've included `babel-standalone` in the docs (which is quite large actually, around 210kB gzipped) and reverted most of the changes, so we can keep the ES6 syntax.
`NodeList.forEach()` is also polyfilled in the docs, thanks for the suggestion.
`whatwg-fetch` was moved to the `devDependencies `-section.

Also, excuse the large diff, it's mostly whitespace which my editor decided to remove ;)

**Comment by t4t5** [comment]
Awesome work, thank you!

**Comment by gmistick** [comment]
I'm still getting Syntax error for => functions , 
Do i need to include any other lib / something else except: <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> ?

**Comment by lionralfs** [comment]
Hey @gmistick 

including 
```html
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
```
should work fine. I just checked IE11 again and everything seems to be working. Are you sure the syntax error is caused by sweetalert? Providing a screenshot of the error message might help us identify the issue.

**Comment by gmistick** [comment]
screenshot from 2017-10-31 16-14-35

**Comment by lionralfs** [comment]
It seems you caused the error yourself by using the (new) arrow function syntax. If you want to use ES6 features in your project while also respecting IE11 compatibility you either have to use some sort of transpiler (I recommend [Babel](http://babeljs.io/)) or writing pure ES5. You should be able to fix the error by changing line 29 to:
```javascript
.then(function(v) { window.location.href = '/login'; });
```

Your error has nothing to do with sweetalert though.

**Comment by gmistick** [comment]
My bad.
Thanks for the prompt response and for your assistance!

**Pull request merged**
