### PR TITLE
generate typescript declaration files & fix some types

### PR DESCRIPTION
**Pull request by Perlmint**
- Provides type info without source files.
- Specific types can provide smarter auto completion in using this library.

### CODE REVIEW

**Comment by t4t5** [comment]
Great stuff! Thanks a lot @Perlmint!

**Comment by t4t5** [comment]
Hmm, is there a way to make TypeScript generate a single `d.ts`-file? There are so many folders added to `dist` now, that I'm afraid it might confuse some users.

**Comment by Perlmint** [comment]
I tried to find the way to generate single `d.ts`file, but I can't the way provided by officially.

After more searching, I found [dts-bundle](https://github.com/TypeStrong/dts-bundle). `dts-bundle` can bundling `d.ts`-files into single file. I think you can try this.

**Comment by t4t5** [comment]
@Perlmint Thanks. Added it in v2.0.4. Give it a try!

**Pull request merged**
