### PR TITLE
Finsished onOpen callback

### PR DESCRIPTION
**Pull request by michaelsmyth94**
Implemented a callback for when the SweetAlert box is opened.

JSFiddle: 
http://jsfiddle.net/w8guq08p/5/

### CODE REVIEW

**Comment by t4t5** [comment]
What's the use case for this?

**Comment by michaelsmyth94** [comment]
I used this for a project I'm working on currently, when clicking on some text (ie a title), I needed to pre-populate the input field with the text of the element clicked, so the user could edit it.

**Comment by t4t5** [comment]
I see. I just added an `inputValue` option in the v1.0.0 release for this. Are there any other use cases (I just want to make sure we don't add lots of unnecessary features that bloat the library)? :)

**Comment by michaelsmyth94** [comment]
Ah that's great! I'm not too sure about other use cases, I can't think of any off the top of my head!

Thanks anyway.

**Comment by t4t5** [comment]
Cool, will close it for now then!

**Comment by wirwolf** [comment]
Please open this request. It's important feature when i want add close icon in  modal.

**Comment by wirwolf** [comment]
When i want add Google reCaptcha into swal, after load html, i need execute this code
`grecaptcha.render(
container,
parameters
)`

**Pull request closed without merging**
