### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tushariscoolster**
Directive added angular js

### CODE REVIEW

**Comment by tushariscoolster** [comment]
?

**Comment by t4t5** [comment]
What are the main advantages compared to the other Angular version?

**Comment by tushariscoolster** [comment]
Other version you need to write javascript code,
Which is though complicated, 
But in this , just html tags are enoughs

**Comment by tushariscoolster** [comment]
@t4t5 ?

**Comment by t4t5** [comment]
I've decided not to add any related projects to the README anymore. Thanks for the PR though!

**Pull request closed without merging**
