### PR TITLE
Add password field option

### PR DESCRIPTION
**Pull request by KnowMoreIT**
Adds an option for a password input as well as a regular input.

### CODE REVIEW

**Comment by jhonmike** [comment]
+1 Password

**Comment by juliofabiane** [comment]
+1 Password

**Comment by viniciusbord9** [comment]
+1 Password

**Comment by ChadTaljaardt** [comment]
:+1:

**Comment by t4t5** [comment]
This is already possible by settings `inputType: "password` in the configurations (sorry for my late reply btw). See "Configurations" further down on this page: http://t4t5.github.io/sweetalert/

**Comment by KnowMoreIT** [comment]
I'm not seeing the option password listed in the configurations on your website. Also when I tried it last year it wouldn't set the input field to password and mask the characters. You can set it to "input" but that doesn't mask the characters like a password field.

Maybe it was updated since I posted this. I will check out the latest build.

**Pull request closed without merging**
