### PR TITLE
adding closing function and making the confirmbutton optional

### PR DESCRIPTION
**Pull request by pascalwacker**
Hi

I really like your work, but unfortunately it didn't fit exactly my needs, so I decided to fork it and modify it.

Basically what I did was making the confirmbutton optional. As default it's still shown, so for all existing users, nothing will change. If someone feels the need to show a sweetalert box without any button, he/she can pass the showConfirmButton param as false and there you go, the button is gone.

The following question is now, how should we close it? Easy! just call `swal(false);`. If you feel like, you can also give an close function as second parameter like `swal(false, function() { alert('Modal is closing'); });`

I hope you like the modifications.

Cheers Pascal Wacker

P.S. I'm so exited, my first github modification :D
P.P.S. I made the minified version with the JS minify plugin for NetBeans, if you prefer something else, let me know.

### CODE REVIEW

**Comment by limonte** [comment]
@pascalwacker I added this feature and some other additional options in [sweetalert2](https://github.com/limonte/sweetalert2).

**Comment by pascalwacker** [comment]
Hi @limonte nice work (:  
  
But how can you trigger a close event in your sweetalert2 plugin? In my case, I'd like to show an overlay with a "well done" or "oops..." message and perform an ajax request in the background. Once the data comes back from the server and is passed to the DOM, the modal should close itself. As I can't predict how long the ajax request will need, I can't use the timer function.
  
Btw. on line 258 you have an error:  
`params.allowEscapeKey = arguments[0].allowEscapeKey !== undefined ? arguments[0].showConfirmButton : defaultParams.allowEscapeKey;`  
  
should be:  
`params.allowEscapeKey = arguments[0].allowEscapeKey !== undefined ? arguments[0].allowEscapeKey : defaultParams.allowEscapeKey;`  
(there's `arguments[0].showConfirmButton` in there). If you tell me how I can fetch your fork, I'd fix it my self ;)

**Comment by limonte** [comment]
> General question about github: Can I also fork your version of sweetalert and contribute directly to that one?

Sure! You can fork sweetalert2 and create pull requests for it.

**Comment by t4t5** [comment]
Forgot about this one. Both features are available in the newer version of SweetAlert, although with a slightly different implementation.
To close the modal, you call ```swal.close()```
To hide the confirmation button, you pass the argument ```showConfirmButton: false```

Thanks for your contribution! :)

**Pull request closed without merging**
