### PR TITLE
[FEATURE] - prompt

### PR DESCRIPTION
**Pull request by mkoczka**
Here is my pull request of prompt feature. Requested in #155

I also updated example website with documentation.

Here is live example - http://mirokoczka.eu/sweetalert/example

### CODE REVIEW

**Comment by t4t5** [comment]
Due to popular demand, I have actively started looking into integrating this in a future release. I want to make some changes though so you're going to have to wait just a little longer. Just letting you guys know. Thanks so much for the contributions! :)

**Comment by bulkan** [comment]
@t4t5 is there an ETA on this feature ?

**Comment by lvillani** [comment]
Any update on this issue? We are using sweetAlert but are investigating vex to add custom prompts to our app but found some problems. Since both libraries lack the features we need we might as well help getting this feature into sweetAlert.

**Comment by craigsheen** [comment]
I think this is being worked on in this PR: https://github.com/t4t5/sweetalert/pull/90

**Comment by lvillani** [comment]
Oh, thanks for pointing me in the right direction!

**Comment by CurosMJ** [comment]
:+1: I wanted this feature. This will now become a replacement for bootstrap modals also.

**Comment by t4t5** [comment]
This has finally landed in v0.5.0 (although with a different implementation)! Download the latest release and follow the last part of this tutorial to get started: https://www.ludu.co/lesson/how-to-use-sweetalert.

Thanks everyone for your suggestions! Keep it sweet!

**Pull request closed without merging**
