### PR TITLE
Added param for changing Cancel button color.

### PR DESCRIPTION
**Pull request by tomcashman**
I've added a parameter for overriding the Cancel button color, similar to the Confirm button.

### CODE REVIEW

**Comment by t4t5** [comment]
This should be changed through CSS (```.sweet-alert button.cancel```). In my opinion, the cancel button should always look the same, since it's not supposed to have any special actions bound to it (except the ones helping the cancellation of actions).

I'm closing for now unless there are big objections to my point of view. :)

**Comment by parterburn** [comment]
@t4t5 I disagree, Cancel is not always an "ignore" action. Here's a scenario we have:

1. User uploads a file, we check if it's a new version of an existing file or brand new file
2. We detect it's probably the same file so we ask the user in a ```swal()``` **Merge File** and  **Don't Merge**. So these are both equally weighted CTA's and neither should be the default greyed out "Cancel" option like we show on other ```swal()``` events.

**Comment by kiide** [comment]
no in css, please in js!

**Comment by xming13** [comment]
+1

**Comment by toadkicker** [comment]
+1 please merge!

**Comment by gerardreches** [comment]
+1

**Comment by albertdick** [comment]
+1

**Pull request closed without merging**
