### PR TITLE
Add ability to specify checkbox as the input type

### PR DESCRIPTION
**Pull request by rbilgil**
It's sometimes needed to have a checkbox on a modal dialog. At present, setting `inputType: 'checkbox'` produces an ugly result with no option for a label. If merged, this pull request would fix that.

A label for the checkbox can be specified with `inputLabel: "Your Label"`, and a label color with `inputLabelColor: "#aabbcc"`.
A boolean callback parameter `checked` is passed through to the doneFunction.

screenshot 2015-08-05 14 43 05
screenshot 2015-08-05 14 40 33
screenshot 2015-08-05 14 40 41

### CODE REVIEW

**Comment by rbilgil** [comment]
The swal function also now accepts a second function to handle the cancel case better. Reverts back to old behaviour if only one function is given.

**Comment by blazeworx** [comment]
:+1:  for this, need it in a current project. @t4t5 any chance we could get this merged in?

**Comment by t4t5** [comment]
I don't want to bloat the library with too many options but this can be achieved with the new [content option](https://sweetalert.js.org/docs/#content) in SweetAlert 2.0.

**Comment by lperry65** [comment]
I've looked at the documentation under #content and there are no examples of using a checkbox. I've tried the following:

`swal({
        title: "This is a test",
        text:  'Using a checkbox!',
        icon: "success",
        content: {
            element: "input",
            attributes: {
                placeholder: "Do not show this again.",
                type: "checkbox",
            },
        },
    });`

But I just get:
capture

Any help would be appreciated thanks.

Lee.

**Comment by lionralfs** [comment]
Hey @lperry65 

This snippet should work:
```js
const content = document.createElement('div');
const input = document.createElement('input');
input.type = 'checkbox';
content.appendChild(input);

swal({
  title: 'This is a test',
  text: 'Using a checkbox!',
  icon: 'success',
  content
});
```

Here's a more complete codepen: https://codepen.io/lionralfs/pen/xWbooW?editors=1010

**Pull request closed without merging**
